In [30]:
import pandas as pd
from pandas import Series, DataFrame
from sklearn import preprocessing

test = preprocessing.LabelEncoder()
test2 = preprocessing.LabelEncoder()
test3 = preprocessing.LabelEncoder()

#to convert into numbers



data= pd.read_csv('train.csv')
frameTrain = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTrain.columns
frameTrain.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTrain.Type = test.fit_transform(frameTrain.Type)
frameTrain.NameSource = test.fit_transform(frameTrain.NameSource)
frameTrain.NameDest = test.fit_transform(frameTrain.NameDest)
print(frameTest[:10])
print("Il y a "+str(len(frameTrain.loc[frameTrain['Label'] == 1]))+" fraudes")
print("Il y a "+str(len(frameTrain.loc[frameTrain['Label'] == 0]))+" opérations correcte")

   Type     Montant  NameSource     SourceB   SourceA  NameDest      DestB  \
0     4  1158070.88        5119  1158070.88      0.00       397       0.00
1     1    67128.33        5929    67128.33      0.00      6102  623880.13
2     1   495002.26        3755    25008.00      0.00       873       0.00
3     4   615954.92         604   615954.92      0.00      4094       0.00
4     1  8994286.69        3411  8994286.69      0.00      3092       0.00
5     1   623152.72        4383   623152.72      0.00      2452  847223.26
6     3    17206.91        6001    90836.00  73629.09      7906       0.00
7     3    20099.71         210    77758.49  57658.77      7594       0.00
8     1   220799.50        2777        0.00      0.00      2130  394666.15
9     1   146729.67        6672   146729.67      0.00      4130       0.00

        DestA  Label
0        0.00      1
1   691008.45      1
2   495002.26      0
3        0.00      1
4  8994286.69      1
5  1470375.97      1
6        0.00      0
7        0.00      0
8   615465.65      0
9   146729.67      1
Il y a 2581 fraudes
Il y a 1997418 opérations correcte

In [25]:
data= pd.read_csv('test.csv')
frameTest = DataFrame(data)
[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTest.columns
frameTest.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTest.Type = test.fit_transform(frameTest.Type)
frameTest.NameSource = test.fit_transform(frameTest.NameSource)
frameTest.NameDest = test.fit_transform(frameTest.NameDest)
print(frameTest[:10])
print("Il y a "+str(len(frameTest.loc[frameTest['Label'] == 1]))+" fraudes")
print("Il y a "+str(len(frameTest.loc[frameTest['Label'] == 0]))+" opérations correcte")

   Type     Montant  NameSource     SourceB   SourceA  NameDest      DestB  \
0     4  1158070.88        5119  1158070.88      0.00       397       0.00
1     1    67128.33        5929    67128.33      0.00      6102  623880.13
2     1   495002.26        3755    25008.00      0.00       873       0.00
3     4   615954.92         604   615954.92      0.00      4094       0.00
4     1  8994286.69        3411  8994286.69      0.00      3092       0.00
5     1   623152.72        4383   623152.72      0.00      2452  847223.26
6     3    17206.91        6001    90836.00  73629.09      7906       0.00
7     3    20099.71         210    77758.49  57658.77      7594       0.00
8     1   220799.50        2777        0.00      0.00      2130  394666.15
9     1   146729.67        6672   146729.67      0.00      4130       0.00

        DestA  Label
0        0.00      1
1   691008.45      1
2   495002.26      0
3        0.00      1
4  8994286.69      1
5  1470375.97      1
6        0.00      0
7        0.00      0
8   615465.65      0
9   146729.67      1
Il y a 3997 fraudes
Il y a 4002 opérations correcte

In [6]:
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

#On test sans les string converties pour le modèle linéaire et le réseau de neuronne
model = SVC(kernel='linear',random_state=0);
modelN = MLPClassifier(random_state=0)


X_train = frameTrain[['Montant','SourceB','SourceA','DestB','DestA']][:2000]
y_train = frameTrain['Label'][:2000]
X_test = frameTest[['Montant','SourceB','SourceA','DestB','DestA']][:2000]
y_test = frameTest['Label'][:2000]

model.fit(X_train,y_train)
modelN.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))
print(modelN.score(X_train,y_train))
print(modelN.score(X_test,y_test))

X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

X_predict = modelN.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

1.0
0.751
0.9995
0.5065
0.495440729483
(1013, 0, 498, 489)
(array([ 0.67041694,  1.        ]), array([ 1.        ,  0.49544073]), array([ 0.80269414,  0.66260163]), array([1013,  987]))
0.0
(1013, 0, 987, 0)
(array([ 0.5065,  0.    ]), array([ 1.,  0.]), array([ 0.67241952,  0.        ]), array([1013,  987]))

/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [7]:
from sklearn import tree


model = tree.DecisionTreeClassifier(random_state=0)

X_train = frameTrain[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

1.0
0.922240280035
0.844883662747
(4000, 2, 620, 3377)
(array([ 0.86580087,  0.99940811]), array([ 0.99950025,  0.84488366]), array([ 0.92785897,  0.91567245]), array([4002, 3997]))

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8,random_state=0)
X_train = frameTrain[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_test = frameTest['Label']
pca.fit(X_train)
X_pca_train = pca.transform(X_train)
X_pca_test = pca.transform(X_test)

In [9]:
model = tree.DecisionTreeClassifier(random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

1.0
0.93186648331

In [10]:
X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

0.863897923443
(4001, 1, 544, 3453)
(array([ 0.88030803,  0.99971048]), array([ 0.99975012,  0.86389792]), array([ 0.93623494,  0.92685546]), array([4002, 3997]))

In [11]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 10,random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.999933999967
0.877359669959

In [12]:
X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

0.754565924443
(4002, 0, 981, 3016)
(array([ 0.80313064,  1.        ]), array([ 1.        ,  0.75456592]), array([ 0.89081803,  0.86011693]), array([4002, 3997]))

In [32]:
import pandas as pd
from pandas import Series, DataFrame
from sklearn import preprocessing
from sklearn import tree

test = preprocessing.LabelEncoder()
test2 = preprocessing.LabelEncoder()
test3 = preprocessing.LabelEncoder()
#to convert into numbers



data= pd.read_csv('train.csv')
frameTrain = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTrain.columns
frameTrain.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTrain.Type = test.fit_transform(frameTrain.Type)
frameTrain.NameSource = test.fit_transform(frameTrain.NameSource)
frameTrain.NameDest = test.fit_transform(frameTrain.NameDest)
print("training set imported")

data= pd.read_csv('predict.csv')
framePredict = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8] = framePredict.columns
framePredict.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA'}, inplace=True)
framePredict.Type = test.fit_transform(framePredict.Type)
framePredict.NameSource = test2.fit_transform(framePredict.NameSource)
framePredict.NameDest = test3.fit_transform(framePredict.NameDest)
print("training set imported")

model = tree.DecisionTreeClassifier(random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = framePredict[['Type','Montant','SourceB','SourceA','DestB','DestA']]

model.fit(X_train,y_train)
print("model trained")

X_predict = model.predict(X_test)
print("model predicted")

training set imported
training set imported
model trained
model predicted

In [33]:
framePredict.Type = test.inverse_transform(framePredict.Type)
framePredict.NameSource = test2.inverse_transform(framePredict.NameSource)
framePredict.NameDest = test3.inverse_transform(framePredict.NameDest)
framePredict['Label'] = X_predict
framePredict

,Type,Montant,NameSource,SourceB,SourceA,NameDest,DestB,DestA,Label
0,TRANSFER,290211.26,C276602564,290211.26,0.00,C58143708,0.00,0.00,1
1,TRANSFER,178344.25,C1280852753,178344.25,0.00,C461887553,0.00,0.00,1
2,CASH_OUT,1023189.90,C1057733607,1023189.90,0.00,C385233047,66259.25,1089449.14,1
3,TRANSFER,592615.53,C366677925,592615.53,0.00,C1433310823,0.00,0.00,1
4,PAYMENT,2632.63,C183500200,0.00,0.00,M1765700212,0.00,0.00,0
5,CASH_IN,60402.09,C113413524,3130888.26,3191290.35,C105834049,1951371.89,1890969.80,0
6,CASH_OUT,152097.84,C1978501596,0.00,0.00,C1937322225,340360.50,492458.34,0
7,CASH_IN,251107.86,C24724881,398483.00,649590.86,C964775275,542145.05,291037.19,0
8,CASH_OUT,75734.99,C109260257,75734.99,0.00,C2020337583,3474246.35,3549981.33,0
9,TRANSFER,493.28,C1723063411,493.28,0.00,C1565674952,0.00,0.00,1
10,PAYMENT,34185.61,C1512170440,7253.00,0.00,M420143361,0.00,0.00,0
11,CASH_OUT,451399.66,C1511096245,451399.66,0.00,C544317728,215513.02,666912.68,1
12,CASH_OUT,371020.35,C1595180363,121994.00,0.00,C917919815,191338.80,562359.15,0
13,CASH_OUT,207261.07,C1856398520,207261.07,0.00,C1898820013,48221.70,255482.77,0
14,TRANSFER,1467987.57,C2035870900,1467987.57,0.00,C1336055115,0.00,0.00,1
15,TRANSFER,1212259.76,C369027158,0.00,0.00,C1788253801,1599697.89,2811957.65,0
16,TRANSFER,19421.77,C499057718,19421.77,0.00,C1899051151,0.00,0.00,1
17,CASH_OUT,844213.81,C1857315735,844213.81,0.00,C541525278,0.00,844213.81,1
18,CASH_OUT,238188.01,C227522091,68284.00,0.00,C961243143,133983.80,372171.81,0
19,CASH_OUT,236914.77,C1406154490,236914.77,0.00,C423223953,175716.84,412631.61,1
20,TRANSFER,10000000.00,C395312314,31343002.08,21343002.08,C554878096,0.00,0.00,1
21,TRANSFER,342988.79,C1522760202,342988.79,0.00,C509783164,0.00,0.00,1
22,PAYMENT,10124.39,C712250859,0.00,0.00,M1357641979,0.00,0.00,0
23,CASH_OUT,93561.29,C1359097606,909.00,0.00,C541801717,0.00,93561.29,0
24,CASH_OUT,50523.78,C1711085884,50523.78,0.00,C1148781766,0.00,50523.78,0
25,TRANSFER,1889351.63,C1587077521,1889351.63,0.00,C1055395176,0.00,0.00,1
26,PAYMENT,36505.02,C1146819885,0.00,0.00,M1497900975,0.00,0.00,0
27,TRANSFER,22117.99,C862057815,22117.99,0.00,C1962362775,0.00,0.00,1
28,TRANSFER,677503.25,C1439879444,677503.25,0.00,C1677398142,0.00,0.00,1
29,CASH_OUT,2562459.56,C1439743203,2562459.56,0.00,C1986745369,0.00,2562459.56,1
...,...,...,...,...,...,...,...,...,...
1969,CASH_IN,154313.42,C1132849204,63.00,154376.42,C53097320,1355755.14,1201441.72,0
1970,TRANSFER,106681.18,C1867725412,106681.18,0.00,C1721123113,0.00,0.00,1
1971,TRANSFER,5239429.19,C1514931968,5239429.19,0.00,C1789156105,0.00,0.00,1
1972,TRANSFER,117683.42,C461302689,117683.42,0.00,C96260697,0.00,0.00,1
1973,CASH_IN,44547.46,C527434968,6244178.66,6288726.11,C108624282,262720.07,218172.62,0
1974,CASH_OUT,1340263.67,C147611805,1340263.67,0.00,C1596756534,371963.94,1712227.61,1
1975,PAYMENT,16201.13,C1809231922,0.00,0.00,M153305731,0.00,0.00,0
1976,CASH_OUT,131312.41,C314056448,0.00,0.00,C499308010,10016681.59,10147994.00,0
1977,CASH_OUT,89809.91,C2049943014,0.00,0.00,C1058399948,103281.31,193091.21,0
1978,PAYMENT,21782.10,C1520307613,15985.71,0.00,M335215952,0.00,0.00,0
1979,CASH_OUT,10000000.00,C210168934,10000000.00,0.00,C1856701476,817443.72,10817443.72,1
1980,CASH_OUT,49388.66,C1718281121,42225.00,0.00,C1310306371,133557.18,182945.83,0
1981,PAYMENT,6177.50,C799389137,0.00,0.00,M1755634918,0.00,0.00,0
1982,TRANSFER,834592.40,C1391274777,834592.40,0.00,C1330816547,0.00,0.00,1
1983,CASH_OUT,261459.81,C1743166559,0.00,0.00,C1017981616,1727238.66,1988698.47,0
1984,CASH_OUT,181224.98,C1087737188,181224.98,0.00,C2145025000,23302.75,204527.73,1
1985,CASH_IN,139285.79,C158134896,0.00,139285.79,C1153280680,478963.28,339677.48,0
1986,CASH_OUT,326250.51,C1592906945,326250.51,0.00,C379003317,83999.86,410250.38,1
1987,TRANSFER,564263.94,C656681397,564263.94,0.00,C1487339522,0.00,0.00,1
1988,CASH_OUT,7596886.83,C1942950399,7596886.83,0.00,C1781043707,1022130.96,8619017.79,1
1989,CASH_OUT,145944.80,C1366476838,145944.80,0.00,C248211897,122425.15,268369.95,1
1990,PAYMENT,22638.85,C1114211691,1286.00,0.00,M1573658334,0.00,0.00,0
1991,CASH_OUT,2324907.08,C1373829253,2324907.08,0.00,C1286348462,157275.18,2482182.26,1
1992,TRANSFER,118462.93,C353172290,118462.93,0.00,C1521894181,0.00,0.00,1
1993,CASH_OUT,758848.47,C444540827,758848.47,0.00,C844469689,9507465.84,10266314.31,1
1994,CASH_OUT,27707.67,C580420882,0.00,0.00,C1183890194,51389.27,79096.94,0
1995,TRANSFER,112363.33,C1783698648,112363.33,0.00,C1902434335,0.00,0.00,1
1996,TRANSFER,10000000.00,C642807002,15912204.00,5912204.00,C177097272,0.00,0.00,1
1997,CASH_OUT,4121986.59,C915028332,4121986.59,0.00,C2135931580,0.00,4121986.59,1
1998,CASH_OUT,1901.24,C283487543,0.00,0.00,C1301127040,93388.35,95289.59,0